name: Deploy to GitHub Pages

# Запускаем магию только на пуши в main
on:
  push:
    branches: main
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
    - uses: actions/checkout@v2
    
      # ставим нужный SDK (можно использовать и более старые)
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
        include-prerelease: true
        
      # генерируем статические файлы
    - name: Publish .NET Core Project
      run: dotnet publish SigmaBallssGitHubPage.Blazor/SigmaBallssGitHubPage.Blazor.csproj -c release --nologo

    - name: Debug publish .Blazor/bin
      run: |
        cd ./SigmaBallssGitHubPage.Blazor/bin/
        ls
      
    - name: Debug publish .Blazor/bin/release
      run: |
        cd ./SigmaBallssGitHubPage.Blazor/bin/release
        ls
        
    - name: Debug publish .Blazor/bin/release/net.9.0
      run: |
        cd ./SigmaBallssGitHubPage.Blazor/bin/release/net9.0
        ls
        
    - name: Debug publish .Blazor/bin/release/wwwroot
      run: |
        cd ./SigmaBallssGitHubPage.Blazor/bin/release/net9.0/wwwroot
        ls
        
    - name: Change base-tag in index.html from / to the necessary
      run: |
        cd ./SigmaBallssGitHubPage.Blazor/bin/
        ls
        sed -i 's/<base href="\/" \/>/<base href="\/sigmaballss.github.io\/" \/>/g' SigmaBallssGitHubPage.Blazor/bin/release/net9.0/wwwroot/index.html
      
    - name: Add .nojekyll file
      run: touch ./SigmaBallssGitHubPage.Blazor/bin/release/net9.0/publish/wwwroot/.nojekyll
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: gh-pages publish
      with:
        branch: gh-pages
        folder: ./SigmaBallssGitHubPage.Blazor/bin/release/net9.0/publish/wwwroot
